# Generated by Django 6.0.4 on 2026-05-26 10:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_event_indexes'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.PositiveSmallIntegerField()),
                ('body', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Wishlist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.RenameIndex(
            model_name='event',
            new_name='events_even_status_dfba18_idx',
            old_name='events_event_status_start_idx',
        ),
        migrations.RenameIndex(
            model_name='event',
            new_name='events_even_organis_118d0c_idx',
            old_name='events_event_organiser_status_idx',
        ),
        migrations.RenameIndex(
            model_name='event',
            new_name='events_even_is_feat_ff8c54_idx',
            old_name='events_event_featured_status_idx',
        ),
        migrations.RenameIndex(
            model_name='event',
            new_name='events_even_is_free_21c6d9_idx',
            old_name='events_event_free_status_idx',
        ),
        migrations.RenameIndex(
            model_name='event',
            new_name='events_even_city_533bd7_idx',
            old_name='events_event_city_idx',
        ),
        migrations.AddField(
            model_name='review',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='events.event'),
        ),
        migrations.AddField(
            model_name='review',
            name='reviewer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='wishlist',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wishlisted_by', to='events.event'),
        ),
        migrations.AddField(
            model_name='wishlist',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wishlisted_events', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='review',
            unique_together={('event', 'reviewer')},
        ),
        migrations.AlterUniqueTogether(
            name='wishlist',
            unique_together={('user', 'event')},
        ),
    ]
