# Generated by Django 6.0.4 on 2026-05-26 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_customuser_indexes'),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='customuser',
            new_name='accounts_cu_account_999baf_idx',
            old_name='accounts_user_account_type_idx',
        ),
        migrations.RenameIndex(
            model_name='customuser',
            new_name='accounts_cu_is_veri_c594de_idx',
            old_name='accounts_user_is_verified_idx',
        ),
        migrations.AddIndex(
            model_name='customuser',
            index=models.Index(fields=['email'], name='accounts_cu_email_5ce40b_idx'),
        ),
    ]
