# Generated by Django 6.0.4 on 2026-05-26 10:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0005_review_wishlist_and_more'),
        ('tickets', '0003_ticket_indexes'),
    ]

    operations = [
        migrations.CreateModel(
            name='TicketTier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('total_slots', models.PositiveIntegerField(default=0)),
                ('sale_start', models.DateTimeField(blank=True, null=True)),
                ('sale_end', models.DateTimeField(blank=True, null=True)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['sort_order', 'price'],
            },
        ),
        migrations.RenameIndex(
            model_name='ticket',
            new_name='tickets_tic_attende_61a065_idx',
            old_name='tickets_ticket_attendee_status_idx',
        ),
        migrations.RenameIndex(
            model_name='ticket',
            new_name='tickets_tic_event_i_d07e31_idx',
            old_name='tickets_ticket_event_status_idx',
        ),
        migrations.RenameIndex(
            model_name='ticket',
            new_name='tickets_tic_ticket__b86ea5_idx',
            old_name='tickets_ticket_code_idx',
        ),
        migrations.AddField(
            model_name='tickettier',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tiers', to='events.event'),
        ),
    ]
